# Site settings
baseURL = "https://example.org/"
languageCode = "en-US"
title = "Four Wheels - One Home"
theme = "hugo-lens-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap", "robotsTXT"]
#copyright = "&copy; TA."

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Header
  [params.header]
    title = "Four Wheels"
    title2 = "One Home"
    description = "Hi! In diesem Bilderblog möchte ich Eindrücke von meinen Reisen festhalten und teilen. Seit einer längeren Reise in die Nordics und Baltics in 2020 habe ich mich in das Leben im Van verliebt. Dabei mag ich besonders mitten in der Natur sein zu können, entlegene Orte zu erkunden und neue Menschen kennenzulernen."

  # Social Icons
  # [[params.social]]
  #   label = "Twitter"
  #   icon = "fa-twitter"
  #   url = "https://twitter.com"

  # [[params.social]]
  #   label = "Instagram"
  #   icon = "fa-instagram"
  #   url = "https://instagram.com"

  # [[params.social]]
  #   label = "Github"
  #   icon = "fa-github"
  #   url = "https://github.com"

  [[params.social]]
    label = "Email"
    icon = "fa-envelope-o"
    url = "mailto:4wheels1home@gmail.com"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://html5up.net/license
